default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: thrifts_user
  password: '1234'
  host: localhost

development:
  <<: *default
  database: thrifts_backend_dev

test:
  <<: *default
  database: thrifts_backend_test
