default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: thrifts_user
  password: '123456'
  host: 127.0.0.1
  port: 5433

development:
  <<: *default
  database: thrifts_backend_dev

test:
  <<: *default
  database: thrifts_backend_test
